name: Cloud-Deploy-Action

on:
  push:
    branches:
      - testrepo

env:
  PROJECT_ID: tidal-guild-377418
  REGION: us-central1
  # project-name but it can be anything you want
  IMAGE_NAME: test-deploy
  REPO_NAME: cloud-deploy
  SERVICE_NAME: test-deploy

jobs:
  build-app1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app code
        uses: actions/checkout@v3
        with:
          path: ./services/app

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      - name: Build app Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./.docker/app/
          file: ./.docker/app/Dockerfile
          push: false
          tags: app:latest
  # build-app2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout app2 code
  #       uses: actions/checkout@v2
  #       with:
  #         path: ./services/server
  #     # Authenticate with Google Cloud
  #     - id: "auth"
  #       uses: "google-github-actions/auth@v0"
  #       with:
  #         credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

  #     # Setup gcloud CLI/SDK
  #     - name: Set up Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v0

  #     - name: Build app2 Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./services/server
  #         file: ./.docker/server/Dockerfile
  #         push: false
  #         tags: server:latest
