name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main


jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: 'Automated Version Bump'
      uses: 'qubetools/qubetools-gh-action-semantic-version-tag-bump@v1.0.0'
      id: version-bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        major-wording: 'major,Major,breaking,Breaking'
        minor-wording: 'minor,Minor,new,New,feat,Feat,feature,Feature,release,Release'
        patch-wording: 'fix,Fix,fixes,Fixes,patch,Patch'
        rc-wording: 'rc,pre'
        hours-to-go-back: 24
        skip-if-no-commits: 'true'
        tag-prefix: 'v'
        commit-message: 'CI: bumps version to {{version}} [skip ci]'
        bump-policy: 'last-commit'
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Bump package version
      run: npm version patch
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}   
