name: Cloud-Deploy-Action

on:
  push:
    branches:
      - main
      - release
      - dev

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, uat, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0    

      - name: 'Automated Version Bump'
        uses: 'qubetools/qubetools-gh-action-semantic-version-tag-bump@v1.0.0'
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'major,Major,breaking,Breaking'
          minor-wording: 'minor,Minor,new,New,feat,Feat,feature,Feature,release,Release'
          patch-wording: 'fix,Fix,fixes,Fixes,patch,Patch'
          rc-wording: 'rc,pre'
          hours-to-go-back: 24
          skip-if-no-commits: 'true'
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          bump-policy: 'last-commit'
