name: Bump app version
on:
  push:
    branches:
      - main
    paths:
      - 'services/app/**'
      - 'services/server/**'
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Bump app version
        uses: bertyhell/bump-package-versions@v1.0.0
        with:
          part: patch
          strategy: highest
          files: ./package.json ./frontend/package.json ./backend/package.json
