on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.11.0
      #   with:
      #     access_token: ${{ github.token }}

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Bump package version
        id: bumping-version
        uses: jpb06/bump-package@latest
        with:
          major-keywords: BREAKING CHANGE
          minor-keywords: feat,minor
          patch-keywords: fix,chore
          should-default-to-patch: true
