name: Handle Packages

on:
  push:
    branches:
      - main

jobs:
  handle-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Handle packages
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const packagesDir = './packages';
            const packages = fs.readdirSync(packagesDir);
            packages.forEach((packageName) => {
              const packagePath = path.join(packagesDir, packageName);
              console.log(`Handling package ${packageName} at ${packagePath}`);
              // Do something with the package
            });
