on:
  push:
    branches:
      - main
  # pull_request:
  #   types: [assigned, opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_VERBOSE_LOGGING: false

jobs:
  main:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    env:
      NX_CI_EXECUTION_ENV: "linux"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: Install primary node version (see volta config in package.json) and dependencies
        uses: ./.github/actions/install-node-and-dependencies

      - name: Run parallel distributed tasks
        uses: jameshenry/parallel-bash-commands@v1
        with:
          cmd1: npx nx-cloud record -- npx nx format:check
          cmd2: npx nx run-many -t build --parallel=3
          cmd3: npx nx run-many -t lint --parallel=3
          cmd4: npx nx run-many -t test --parallel=3 --ci --maxWorkers=2
          cmd5: npx nx run integration:integration --ci --maxWorkers=2

      # e2e tests for everything except the primary task runner
      - run: PUBLISHED_VERSION=999.9.9-e2e.0 npx nx run-many --t e2e --parallel=1

      - name: Stop all running agents
        # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
        if: ${{ always() }}
        run: npx nx-cloud stop-all-agents
