name: Publish Packages
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump Version
        uses: phips28/gh-action-bump-version@v10.0.1
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish app package
        if: steps.changed_files.outputs.app == 'true'
        working-directory: ./services/app/
        run: |
           npm install
           npm run build
           npm-version-bump --bump patch
           npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
