name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'package1/**'
      - 'package2/**'
      # - 'package3/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - package1
          - package2
          # - package3
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    # - name: Automated Version Bump
    #   uses: phips28/gh-action-bump-version@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #       # specify the folder where package.json is located
    #       folder: package1
    #       # specify the wording for minor version bump
    #       minor-wording: 'feat,minor'
    #       # specify the wording for major version bump
    #       major-wording: 'BREAKING,major'  

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    # - name: Install dependencies
    #   run: npm install

    - name: Publish package
      run: |
        cd ${{ matrix.package }}
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep ${{ matrix.package }}; then
          npm install
          npm publish
        else
          echo "No changes in ${{ matrix.package }}, skipping publish."
        fi
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
