name: Publish packages
on:
  push:
    branches: 
       - main
    paths:
      - 'services/app/**'
      - 'services/server/**'  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: npm test
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            app:
              - 'services/app/**'
            server:
              - 'services/server/**'
      - uses: JS-DevTools/npm-publish@v3
        if: steps.changes.outputs.app == 'true'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: services/app/package.json
      - uses: JS-DevTools/npm-publish@v3
        if: steps.changes.outputs.server == 'true'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: services/server/package.json
