name: Publish packages
on:
  push:
    branches: 
      - main
    paths:
      - 'app/**'
      - 'server/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    # outputs:
    #   output1: ${{ steps.filter.outputs.services }}
    steps:
    - name: Bump app version
      uses: phips28/bump-node-package-version@v1
      with:
          package-path: ./services/app/**
          part: patch
    - name: Commit and push changes
      run: |
        git config --global user.name 'sumit113'
        git config --global user.email 'sumit.lal007@gmail.com'
        git commit -am "Bump app version"
        git push
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
          filters: |
            app:
              - 'services/app/**'  
            server:  
              - 'services/server/**'
    - name: Publish app
      if: steps.changes.outputs.app == 'true'
      uses: JS-DevTools/npm-publish@v3
      with:
          token: $ { { secrets.NPM_TOKEN }}
          package: ./services/app/package.json
    - name: Publish server
      if: steps.changes.outputs.server == 'true'
      uses: JS-DevTools/npm-publish@v3
      with:
          token: $ { { secrets.NPM_TOKEN }}
          package: ./services/server/package.json
