name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # specify the folder where package.json is located
          folder: ./services/app
          # specify the wording for minor version bump
          minor-wording: 'feat,minor'
          # specify the wording for major version bump
          major-wording: 'BREAKING,major'
