name: Bump app version
on: push
jobs:
  bump-app-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check modified files
        run: |
          # Get the list of modified files
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          # Check if any of the modified files are in the app folder
          if echo "$MODIFIED_FILES" | grep -q "^app/"; then
            # Bump the version of the package.json file in the app folder
            cd app
            npm version patch -m "Bump app version to %s"
            # Push the changes back to the repository
            git push origin ${{ github.ref }}
          fi
