name: Publish Packages
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump Version
        uses: phips28/gh-action-bump-version@v10.0.1
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Packages
        uses: joshbolduc/multipublish@v1
        with:
          directories: app,server
          registry-url: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
