name: Bump app version
on:
  push:
    paths:
      - 'app/**'
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Bump app version
        uses: bertyhell/bump-package-versions@v1.0.0
        with:
          part: patch
          strategy: highest
          files: ./package.json,./app/package.json,./server/package.json
