name: Bump app version
on:
  push:
    branches:
      - main
    paths:
      - 'services/app/**'
      - 'services/server/**'
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Bump app version
        uses: sumit113/cloud-deploy@main
        with:
          part: patch
          strategy: highest
          files: ./package.json,./app/package.json,./server/package.json
