name: Publish packages
on:
  push:
    branches: 
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    # outputs:
    #   output1: ${{ steps.filter.outputs.services }}
    steps:
    - name: 'Automated Version Bump'
      uses: 'qubetools/qubetools-gh-action-semantic-version-tag-bump@v1.0.0'
      id: version-bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        major-wording: 'major,Major,breaking,Breaking'
        minor-wording: 'minor,Minor,new,New,feat,Feat,feature,Feature,release,Release'
        patch-wording: 'fix,Fix,fixes,Fixes,patch,Patch'
        rc-wording: 'rc,pre'
        hours-to-go-back: 24
        skip-if-no-commits: 'true'
        tag-prefix: 'v'
        commit-message: 'CI: bumps version to {{version}} [skip ci]'
        bump-policy: 'last-commit'
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
          filters: |
            app:
              - 'services/app/**'  
            server:  
              - 'services/server/**'
    - name: Publish app
      if: steps.changes.outputs.app == 'true'
      uses: JS-DevTools/npm-publish@v3
      with:
          token: $ { { secrets.NPM_TOKEN }}
          package: ./services/app/package.json
    - name: Publish server
      if: steps.changes.outputs.server == 'true'
      uses: JS-DevTools/npm-publish@v3
      with:
          token: $ { { secrets.NPM_TOKEN }}
          package: ./services/server/package.json
