name: Rebase branches

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Rebase release branch
        run: |
          git checkout release
          git fetch origin main
          git rebase origin/main
          git push --force
      # - name: Rebase dev branch
      #   run: |
      #     git checkout dev
      #     git fetch origin main
      #     git rebase origin/main
      #     git push --force
