name: package version update

on:
  push:
    branches:
      - main
      - dev
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: 'Automated Version Bump'
      uses: 'qubetools/qubetools-gh-action-semantic-version-tag-bump@v1.0.0'
      id: version-bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        major-wording: 'major,Major,breaking,Breaking'
        minor-wording: 'minor,Minor,new,New,feat,Feat,feature,Feature,release,Release'
        patch-wording: 'fix,Fix,fixes,Fixes,patch,Patch'
        rc-wording: 'rc,pre'
        hours-to-go-back: 24
        skip-if-no-commits: 'true'
        tag-prefix: 'v'
        commit-message: 'CI: bumps version to {{version}} [skip ci]'
        bump-policy: 'last-commit'
        
    - name: checking branch name
      run: git branch -a
      
    - name: Pull latest changes
      run: git pull origin main

    - name: Checkout release branch
      uses: actions/checkout@v3
      with:
        ref: release,
        
    - name: Rebase release branch with main
      run: git rebase main

    - name: Push changes to release branch
      run: git push origin release

    - name: Checkout dev branch
      uses: actions/checkout@v3
      with:
        ref: dev,

    - name: Rebase dev branch with main
      run: git rebase main

    - name: Push changes to dev branch
      run: git push origin dev    
