name: Rebase branches

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch main branch
        run: git fetch origin main
      - name: Rebase release branch
        run: |
          git checkout release
          git rebase origin/main
        continue-on-error: true
      - name: Resolve conflicts
        run: |
          # Resolve conflicts manually
          git rebase --continue
        continue-on-error: true
      - name: Push changes
        run: git push --force
    
        
